---
driver:
  name: vagrant
  ssh:
    shell: '"/bin/sh"'

driver_config:
  require_chef_omnibus: latest
  # require_chef_omnibus: 12.4.1
  # require_chef_omnibus: 11.18.14

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.1
  - name: debian-7.8
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.1
  - name: centos-6.6
  - name: fedora-21
  - name: fedora-20
  - name: freebsd-9.3
  - name: freebsd-10.1

suites:
  - name: default
    run_list:
     - recipe[system::default]
     - recipe[system::timezone]
     - recipe[system::install_packages]
     - recipe[system::uninstall_packages]
     - recipe[system::profile]
     - recipe[system::environment]
    attributes:
      system:
        short_hostname: test
        domain_name: kitchen
        environment:
          extra:
           DINNER: Pizza
           DESERT: Ice cream
        timezone: Australia/Sydney
        static_hosts:
          95.211.29.66: supermarket.io
          184.106.28.82: chef.io
        packages:
          install:
           - "curl"
           - "wget"
          install_compile_time:
           - "sudo"
          uninstall:
           - "gcc"
        profile:
          append_scripts:
           - "export CHEF_IS_AWESOME=1"
           - "echo helloworld > /dev/null"
          path_append: true
          path:
            - "/opt/local/bin"
            - "/opt/local/food/bin"
