sudo: false

language: ruby
cache: bundler

rvm:
  - 2.2.2
  - 2.1.6
  - 2.0.0-p645

bundler_args: --without development integration

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"

before_script:
  - bundle exec berks install

script:
  - bundle exec foodcritic -f any .
  - bundle exec rubocop
